[package]
name = "bridge"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "bridge"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

bridge_integrity = { workspace = true } 
